# Generated by Django 4.1 on 2022-09-06 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_shop_product_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date_posted',
            new_name='date_created',
        ),
    ]
