# Generated by Django 4.1 on 2022-09-06 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_title_product_name_product_brand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='stock',
        ),
    ]
