# Generated by Django 4.1 on 2022-09-08 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
